# Create a PR from develop -> master
name: Create deployment PR

on:
  push:
    branches: [develop]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Must have read/write permission to the repo
          title: Deploy to prod
          source_branch: develop
          target_branch: main
