# Check if a 'deploy' label has been added to the PR
# If so, merge the PR using rebase method and delete source branch
name: Merge Bot

on:
  pull_request:
    types:
      - labeled
      - synchronize
      - ready_for_review
  pull_request_review:
    types:
      - dismissed
      - submitted
jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge
    steps:
    - name: Merge PR
      uses: squalrus/merge-bot@v0.1.0
      with:
        test: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        reviewers: true
        labels: deploy
        blocking_labels: do not merge
        checks_enabled: true
        method: rebase
